const $=id=>document.getElementById(id),native=typeof google!=='undefined'&&!!google.script?.run;
const KEY='quality-planner-v2',uuid=()=>crypto.randomUUID();
let draft={schemaVersion:2,projectId:uuid(),editKey:uuid()+uuid(),student:{name:'',studentId:'',grade:'四年級',className:'',track:'醫院品質管理企劃課'},sections:Object.fromEntries(SCHEMA.map(s=>[s.id,initialSection(s)])),saved:{},active:0},pending={},busy=false,finalRequest=null;
let oldNotice='';try{const old=localStorage.getItem(KEY);if(old){const parsed=JSON.parse(old);validateBackup(parsed);if(parsed.schemaVersion===2&&parsed.sections)draft=parsed;}else if(localStorage.getItem('quality-planner-v1'))oldNotice='偵測到舊版草稿。舊版文字仍保留於瀏覽器；請下載舊版備份作為參考後，改填新版逐欄表格。';}catch(e){oldNotice='無法讀取本機草稿。請匯入備份。';}
const identityMap={studentName:'name',studentId:'studentId',grade:'grade',className:'className',track:'track'};
Object.entries(identityMap).forEach(([id,k])=>{$(id).value=draft.student[k]||'';$(id).oninput=()=>{draft.student[k]=$(id).value.trim();SCHEMA.forEach(s=>delete draft.saved[s.id]);persist();updateProgress();};});
$('connection').textContent=native?'雲端存檔版：每段按「存檔」後寫入教師 Google Sheet，收到回執才算成功。':WEB_APP_URL?'此頁可本機填寫；雲端存檔請開啟下方教師系統，先下載備份並於雲端版匯入。':'目前可逐段填寫與本機存檔；指定帳號的 GAS 尚待建立／部署，Google Sheet 寫入未啟用。';
if(!native&&WEB_APP_URL){const a=document.createElement('a');a.href=WEB_APP_URL;a.target='_blank';a.className='button';a.textContent='開啟教師雲端存檔版';$('connection').append(document.createElement('br'),a);}
$('globalStatus').textContent=oldNotice;
function persist(){try{localStorage.setItem(KEY,JSON.stringify(draft));return true;}catch(e){$('globalStatus').textContent='此瀏覽器無法儲存草稿，請下載備份。';return false;}}
function markDirty(id){delete draft.saved[id];delete pending[id];persist();updateProgress();$('state-'+id).textContent='內容已更新，請按存檔；輸入內容已盡可能自動保存在本機草稿。';}
function fieldControl(sec,f,row,index){const wrap=document.createElement('div'),label=document.createElement('label'),id=sec.id+'-'+index+'-'+f.key;label.textContent=f.label+(f.optional?'（選填）':'');label.htmlFor=id;let input;
 if(f.type==='multi'){input=document.createElement('fieldset');input.setAttribute('aria-label',sec.title+'第'+(index+1)+'列 '+f.label);f.options.forEach(option=>{const l=document.createElement('label'),c=document.createElement('input');c.type='checkbox';c.checked=(row[f.key]||[]).includes(option);c.onchange=()=>{const set=new Set(row[f.key]||[]);c.checked?set.add(option):set.delete(option);row[f.key]=[...set];markDirty(sec.id)};l.append(c,document.createTextNode(option));input.append(l)});}
 else{input=document.createElement(f.type==='textarea'?'textarea':f.type==='select'?'select':'input');input.id=id;input.setAttribute('aria-label',sec.title+(sec.repeat?' 第'+(index+1)+'列':'')+' '+f.label);if(f.type==='select')f.options.forEach(v=>input.add(new Option(v,v)));else if(f.type!=='textarea'){input.type=['number','integer'].includes(f.type)?'number':f.type==='date'?'date':f.type==='url'?'url':'text';if(['number','integer'].includes(f.type)){input.min=f.type==='integer'?'0':'0.5';input.step=f.type==='integer'?'1':'0.5';}}
 input.value=row[f.key]||'';input.maxLength=['need','intro','purpose'].includes(sec.id)?1000:3000;input.oninput=()=>{row[f.key]=input.value;markDirty(sec.id);if(sec.id==='t4')updateHours()};}
 wrap.append(label,input);if(f.hint){const hint=document.createElement('p');hint.className='hint';hint.textContent=f.hint;wrap.append(hint)}return wrap;}
function renderSection(sec,i){let panel=$('section-'+sec.id);if(!panel){panel=document.createElement('section');panel.id='section-'+sec.id;panel.className='panel';$('sections').append(panel);}panel.replaceChildren();panel.hidden=i!==draft.active;
 const h=document.createElement('h2');h.textContent=sec.title;const guide=document.createElement('p');guide.className='note';guide.textContent=sec.guide;panel.append(h,guide);
 if(sec.repeat){const hint=document.createElement('p');hint.className='hint';hint.textContent='每一列獨立填寫。表格可左右滑動查看全部欄位；按「新增一列」增加工作任務或單元。';panel.append(hint);const scroll=document.createElement('div');scroll.className='tablewrap';const table=document.createElement('table'),caption=document.createElement('caption');caption.textContent=sec.title+'填寫表格';table.append(caption);const head=document.createElement('thead'),tr=document.createElement('tr');['列次',...sec.fields.map(f=>f.label),'操作'].forEach(v=>{const th=document.createElement('th');th.scope='col';th.textContent=v;tr.append(th)});head.append(tr);table.append(head);const body=document.createElement('tbody');draft.sections[sec.id].forEach((row,j)=>{const tr=document.createElement('tr'),n=document.createElement('td');n.textContent=j+1;tr.append(n);sec.fields.forEach(f=>{const td=document.createElement('td');td.append(fieldControl(sec,f,row,j));tr.append(td)});const td=document.createElement('td'),del=document.createElement('button');del.textContent='移除第'+(j+1)+'列';del.className='secondary';del.disabled=draft.sections[sec.id].length===1;del.onclick=()=>{if(confirm('移除這一列？')){draft.sections[sec.id].splice(j,1);markDirty(sec.id);renderSection(sec,i)}};td.append(del);tr.append(td);body.append(tr)});table.append(body);scroll.append(table);panel.append(scroll);const add=document.createElement('button');add.className='secondary';add.textContent='新增一列';add.onclick=()=>{if(draft.sections[sec.id].length>=30){setMessage(sec.id,'每張表最多30列');return}draft.sections[sec.id].push(Object.fromEntries(sec.fields.map(f=>[f.key,emptyValue(f)])));markDirty(sec.id);renderSection(sec,i)};panel.append(add);}
 else sec.fields.forEach(f=>panel.append(fieldControl(sec,f,draft.sections[sec.id],0)));
 if(sec.id==='t4'){const p=document.createElement('p');p.id='hoursTotal';panel.append(p);updateHours();}
 const example=document.createElement('button');example.textContent='載入本段教學範例';example.className='secondary';example.onclick=()=>{if(confirm('將覆蓋本段內容，是否載入模擬範例？')){draft.sections[sec.id]=JSON.parse(JSON.stringify(EXAMPLES[sec.id]).replaceAll('〔場域〕',draft.student.track.startsWith('醫院')?'醫院':'長照機構'));markDirty(sec.id);renderSection(sec,i);}};panel.append(example);
 const actions=document.createElement('div');actions.className='actions';const prev=document.createElement('button');prev.textContent='上一段';prev.className='secondary';prev.disabled=i===0;prev.onclick=()=>go(i-1);const save=document.createElement('button');save.textContent=native?'存檔到 Google Sheet':'存檔到本機';save.dataset.save=sec.id;save.onclick=()=>saveSection(sec.id);const download=document.createElement('button');download.textContent='下載本段備份';download.className='secondary';download.onclick=()=>downloadJSON({...draft,sections:{[sec.id]:draft.sections[sec.id]},partial:true,sectionId:sec.id},sec.title+'備份.json');const next=document.createElement('button');next.textContent='下一段';next.className='secondary';next.disabled=i===SCHEMA.length-1;next.onclick=()=>go(i+1);actions.append(prev,save,download,next);panel.append(actions);
 const state=document.createElement('p');state.id='state-'+sec.id;state.className='meta statusline';state.textContent=draft.saved[sec.id]?('已存檔：'+draft.saved[sec.id].at+' · '+draft.saved[sec.id].where):'尚未按存檔；可先儲存未完成的草稿。';const message=document.createElement('p');message.id='message-'+sec.id;message.className='message';message.setAttribute('role','status');panel.append(state,message);}
function updateHours(){if(!$('hoursTotal'))return;const total=draft.sections.t4.reduce((sum,r)=>sum+Number(r.hours||0),0);$('hoursTotal').textContent='表4合計：'+total+'小時；課程總時數：'+(draft.sections.info.hours||'尚未填寫')+'小時。'}
function render(){ $('nav').replaceChildren();SCHEMA.forEach((s,i)=>{const b=document.createElement('button');b.textContent=(i+1)+'. '+s.title;b.dataset.section=s.id;b.onclick=()=>go(i);$('nav').append(b);renderSection(s,i)});updateProgress();go(draft.active,false);}
function go(i,scroll=true){draft.active=Math.max(0,Math.min(SCHEMA.length-1,i));SCHEMA.forEach((s,j)=>{$('section-'+s.id).hidden=j!==draft.active;const b=document.querySelector('nav button[data-section="'+s.id+'"]');b.setAttribute('aria-current',j===draft.active?'step':'false')});persist();if(scroll)$('sections').scrollIntoView({behavior:'smooth',block:'start'});}
function updateProgress(){const filled=SCHEMA.filter(s=>sectionErrors(s,draft.sections[s.id]).length===0).length,saved=Object.keys(draft.saved).length;$('progress').textContent='已符合段落必填：'+filled+'／'+SCHEMA.length+'；已按存檔：'+saved+'／'+SCHEMA.length;}
function setMessage(id,message){$('message-'+id).textContent=message;}
function identityErrors(){return ['name','studentId','grade','className'].filter(k=>!draft.student[k]?.trim()).map(k=>({name:'姓名',studentId:'學號',grade:'年級',className:'班級'}[k]));}
function rpc(name,payload){return new Promise((resolve,reject)=>google.script.run.withSuccessHandler(resolve).withFailureHandler(reject)[name](payload));}
async function saveSection(id){if(busy)return;const sec=SCHEMA.find(s=>s.id===id),errors=sectionErrors(sec,draft.sections[id]);if(!native){const at=new Date().toLocaleString('zh-TW');draft.saved[id]={at,where:'本機存檔'};if(persist()){$('state-'+id).textContent='已存檔於本機：'+at;setMessage(id,errors.length?'草稿已存檔；仍需完成：\n'+errors.join('\n'):'本段已完成並存檔。Google Sheet 尚未寫入。');}else delete draft.saved[id];updateProgress();return;}
 if(identityErrors().length){setMessage(id,'雲端存檔前請填：'+identityErrors().join('、'));return}if(!$('classCode').value.trim()){setMessage(id,'請填教師提供的課程代碼');return}if(!$('consent').checked){setMessage(id,'請先勾選資料用於課堂評量的確認欄。');return}
 const content=JSON.stringify(draft.sections[id]),student=JSON.stringify(draft.student);let request=pending[id];if(!request||request.content!==content||request.student!==student)pending[id]=request={id:uuid(),content,student};
 busy=true;document.querySelectorAll('button[data-save]').forEach(b=>b.disabled=true);setMessage(id,'正在存入教師 Google Sheet…');
 try{const r=await rpc('saveSection',{schemaVersion:2,projectId:draft.projectId,editKey:draft.editKey,requestId:request.id,classCode:$('classCode').value.trim(),student:draft.student,sectionId:id,content:JSON.parse(content)});if(content===JSON.stringify(draft.sections[id])&&student===JSON.stringify(draft.student)){draft.saved[id]={at:r.savedAt,where:'Google Sheet',receipt:r.receipt};delete pending[id];persist();$('state-'+id).textContent='已存入 Google Sheet：'+r.savedAt;}setMessage(id,'儲存成功，回執：'+r.receipt+(errors.length?'\n仍待完成：\n'+errors.join('\n'):''));}
 catch(e){setMessage(id,'未確認儲存成功：'+e.message+'。已保留草稿，可重試。');}finally{busy=false;document.querySelectorAll('button[data-save]').forEach(b=>b.disabled=false);updateProgress();}}
function downloadJSON(value,filename){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('backup').onclick=()=>downloadJSON(draft,'品質企劃完整備份.json');
function validateBackup(d){if(d?.schemaVersion!==2||!d.sections||!d.student||typeof d.projectId!=='string'||typeof d.editKey!=='string')throw Error('僅支援新版逐欄備份；舊版備份請保留作為填表參考。');for(const [id,content] of Object.entries(d.sections)){const sec=SCHEMA.find(s=>s.id===id);if(!sec)throw Error('未知段落');const rows=sec.repeat?content:[content];if(!Array.isArray(rows)||!rows.length||rows.length>30)throw Error('表格列數不符');for(const row of rows)for(const f of sec.fields){const v=row[f.key];if(f.type==='multi'){if(!Array.isArray(v)||v.some(x=>!f.options.includes(x)))throw Error('複選內容不符');}else if(typeof v!=='string'||v.length>3000)throw Error('欄位內容不符');}}}
$('import').onchange=async e=>{try{const d=JSON.parse(await e.target.files[0].text());validateBackup(d);if(!confirm('匯入會覆蓋'+(d.partial?'本段':'整份')+'內容；建議先下載目前備份。'))return;if(d.partial){draft.sections[d.sectionId]=d.sections[d.sectionId];delete draft.saved[d.sectionId];}else{draft=d;draft.active=0;pending={};}Object.entries(identityMap).forEach(([id,k])=>$(id).value=draft.student[k]||'');persist();render();$('globalStatus').textContent='備份已匯入。';}catch(err){$('globalStatus').textContent='匯入失敗：'+err.message;}e.target.value='';};
$('loadCloud').onclick=async()=>{if(!native){$('globalStatus').textContent='請先開啟教師雲端存檔版，並匯入您的完整備份。';return}if(!$('classCode').value.trim()){$('globalStatus').textContent='請輸入課程代碼';return}if(!confirm('讀回雲端存檔會覆蓋本機已有的同段內容，請先下載備份。'))return;try{const result=await rpc('loadProposal',{projectId:draft.projectId,editKey:draft.editKey,classCode:$('classCode').value.trim()});Object.assign(draft.sections,result.sections);draft.saved=result.saved;draft.student=result.student;Object.entries(identityMap).forEach(([id,k])=>$(id).value=draft.student[k]||'');persist();render();$('globalStatus').textContent='已讀回自己的雲端存檔。';}catch(e){$('globalStatus').textContent='讀取失敗：'+e.message;}};
$('reset').onclick=()=>{if(confirm('開始新企劃並清除本機草稿？雲端歷史不會刪除，請先下載備份。')){try{localStorage.removeItem(KEY)}catch(e){}location.reload();}};
$('review').onclick=()=>{const errors=proposalErrors(draft);$('reviewResult').textContent=errors.length?errors.join('\n'):'整份企劃已通過必填、時數與代碼對應檢查。';};
$('submit').onclick=async()=>{const errors=proposalErrors(draft);if(errors.length){$('reviewResult').textContent='請先修正：\n'+errors.join('\n');return}if(!$('consent').checked){$('reviewResult').textContent='請勾選資料用於課堂評量的確認欄。';return}if(!native){$('reviewResult').textContent='完整檢核通過，但此頁尚未連接 Google Sheet。請下載備份後在雲端存檔版匯入。';return}if(!$('classCode').value.trim()){$('reviewResult').textContent='請輸入教師課程代碼';return}$('submit').disabled=true;try{const r=await rpc('submitProposal',{...draft,requestId:(()=>{const signature=JSON.stringify({student:draft.student,sections:draft.sections});if(!finalRequest||finalRequest.signature!==signature)finalRequest={id:uuid(),signature};return finalRequest.id;})(),classCode:$('classCode').value.trim()});SCHEMA.forEach(s=>draft.saved[s.id]={at:r.savedAt,where:'Google Sheet',receipt:r.receipt});persist();updateProgress();finalRequest=null;$('reviewResult').textContent='完整企劃已提交並存檔。回執：'+r.receipt+'\n時間：'+r.savedAt;}catch(e){$('reviewResult').textContent='未確認整份提交成功：'+e.message;}finally{$('submit').disabled=false;}};
$('print').onclick=()=>{const report=$('report');report.replaceChildren();const h=document.createElement('h1');h.textContent='品質管理企劃報告';const p=document.createElement('p');p.textContent=draft.student.name+'／'+draft.student.studentId+'／'+draft.student.grade+'／'+draft.student.className+'\n'+draft.student.track;report.append(h,p);SCHEMA.forEach(sec=>{const section=document.createElement('section'),h=document.createElement('h2');h.textContent=sec.title;section.append(h);if(sec.repeat){const table=document.createElement('table'),tr=document.createElement('tr');sec.fields.forEach(f=>{const th=document.createElement('th');th.textContent=f.label;tr.append(th)});table.append(tr);draft.sections[sec.id].forEach(row=>{const tr=document.createElement('tr');sec.fields.forEach(f=>{const td=document.createElement('td');td.textContent=Array.isArray(row[f.key])?row[f.key].join('、'):row[f.key];tr.append(td)});table.append(tr)});section.append(table)}else sec.fields.forEach(f=>{const h=document.createElement('h3'),p=document.createElement('p');h.textContent=f.label;p.textContent=draft.sections[sec.id][f.key];section.append(h,p)});report.append(section)});window.print();};
render();

$('caseLoad').onclick=()=>{if(!confirm('載入完整教學案例會覆蓋全部企劃內容，保留學生資料；請先下載目前備份。案例全部為虛構，不會自動提交。'))return;draft.sections=JSON.parse(JSON.stringify(TEACHING_CASE.sections));draft.student.track=TEACHING_CASE.track;draft.projectId=uuid();draft.editKey=uuid()+uuid();draft.saved={};draft.active=0;pending={};finalRequest=null;$('track').value=draft.student.track;persist();render();$('globalStatus').textContent='已載入完整虛構長照案例。請逐段操作與存檔；目前未自動提交。';};
