const OWNER_EMAIL='chatgpt.cjcu@gmail.com';
const EXISTING_SHEET_ID=''; // 可於私有安裝稿指定已建立的收件試算表
const SCHEMA=__SCHEMA__;
__VALIDATION__
function setup(){
 if(Session.getEffectiveUser().getEmail().toLowerCase()!==OWNER_EMAIL)throw Error('請用 '+OWNER_EMAIL+' 執行 setup；未建立任何資料。');
 const p=PropertiesService.getScriptProperties();let id=p.getProperty('SHEET_ID')||EXISTING_SHEET_ID;
 if(id&&!p.getProperty('SHEET_ID'))p.setProperty('SHEET_ID',id);
 if(!id){const ss=SpreadsheetApp.create('大四品質管理企劃｜逐段逐表存檔');id=ss.getId();p.setProperty('SHEET_ID',id);}
 const ss=SpreadsheetApp.openById(id);ensureSheet_(ss,'企劃索引',['企劃識別碼','續填密鑰雜湊','建立時間','姓名','學號','年級','班級','主題']);
 SCHEMA.forEach(sec=>ensureSheet_(ss,sheetName_(sec),headers_(sec)));
 ensureSheet_(ss,'完整提交',['回執','提交時間','企劃識別碼','姓名','學號','年級','班級','主題','狀態']);
 if(!p.getProperty('CLASS_CODE'))p.setProperty('CLASS_CODE',Utilities.getUuid());
 console.log('教師帳號：'+OWNER_EMAIL);console.log('教師試算表：https://docs.google.com/spreadsheets/d/'+id);console.log('課程代碼（請私下交給學生）：'+p.getProperty('CLASS_CODE'));
}
function doGet(){return HtmlService.createHtmlOutputFromFile('Index').setTitle('品質管理企劃教室｜逐表填寫').addMetaTag('viewport','width=device-width, initial-scale=1');}
function sheetName_(sec){return sec.title.replace(/[\\/?*\[\]:]/g,'').slice(0,90);}
function headers_(sec){return ['回執','存檔時間','企劃識別碼','姓名','學號','年級','班級','主題','資料狀態','列次',...sec.fields.map(f=>f.label),'段落JSON（續填用）'];}
function ensureSheet_(ss,name,headers){let s=ss.getSheetByName(name);if(!s)s=ss.insertSheet(name);if(!s.getLastRow()){s.getRange(1,1,1,headers.length).setValues([headers]);s.setFrozenRows(1);s.getRange(1,1,1,headers.length).setBackground('#eeeeee').setFontWeight('bold').setWrap(true);s.setRowHeight(1,42);}return s;}
function safeCell_(value){if(typeof value==='number')return value;const v=Array.isArray(value)?value.join('、'):String(value??'');return /^\s*[=+@-]/.test(v)||/^\d+$/.test(v)?"'"+v:v;}
function authorize_(d){const p=PropertiesService.getScriptProperties();if(!d||!p.getProperty('CLASS_CODE')||d.classCode!==p.getProperty('CLASS_CODE'))throw Error('課程代碼不正確');for(const k of ['projectId','editKey'])if(typeof d[k]!=='string'||!/^[a-zA-Z0-9-]{30,90}$/.test(d[k]))throw Error('企劃識別或續填密鑰不正確');const id=p.getProperty('SHEET_ID');if(!id)throw Error('教師尚未完成setup');return SpreadsheetApp.openById(id);}
function hash_(s){return Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,s).map(b=>('0'+((b+256)%256).toString(16)).slice(-2)).join('');}
function date_(){return Utilities.formatDate(new Date(),'Asia/Taipei','yyyy-MM-dd HH:mm:ss');}
function student_(s){if(!s)throw Error('學生資料必填');for(const k of ['name','studentId','grade','className','track'])if(typeof s[k]!=='string'||!s[k].trim()||s[k].length>100)throw Error('學生姓名、學號、年級、班級與主題必填');if(!['四年級','三年級','二年級','一年級','其他年級','不適用（教師／作者）'].includes(s.grade))throw Error('年級不正確');if(!['醫院品質管理企劃課','長照機構品質管理企劃課','宮廟管理職能導向種子師資培訓課程'].includes(s.track))throw Error('主題不正確');if(s.grade==='不適用（教師／作者）'&&s.studentId!=='不適用（作者）')throw Error('作者身分請使用不適用學號');return Object.fromEntries(['name','studentId','grade','className','track'].map(k=>[k,s[k].trim()]));}
function checkOwnership_(ss,d,create){const sheet=ss.getSheetByName('企劃索引');if(!sheet)throw Error('教師尚未初始化企劃索引');const rows=sheet.getLastRow()>1?sheet.getRange(2,1,sheet.getLastRow()-1,8).getValues():[],row=rows.find(r=>r[0]===d.projectId);if(row){if(row[1]!==hash_(d.editKey))throw Error('續填密鑰不符，不能存取這份作業');if(create){const st=student_(d.student),idx=rows.indexOf(row)+2;sheet.getRange(idx,4,1,5).setValues([[st.name,st.studentId,st.grade,st.className,st.track].map(safeCell_)]);}
 return row;}if(!create)throw Error('尚無這份企劃的雲端存檔');const s=student_(d.student);sheet.appendRow([d.projectId,hash_(d.editKey),date_(),s.name,s.studentId,s.grade,s.className,s.track].map(safeCell_));return null;}
function sanitizeContent_(sec,content){const rows=sec.repeat?content:[content];if(!Array.isArray(rows)||rows.length<1||rows.length>30)throw Error('每表需1到30列');const result=rows.map(row=>{if(!row||typeof row!=='object'||Array.isArray(row))throw Error('欄位格式不正確');const out={};for(const f of sec.fields){const value=row[f.key];if(f.type==='multi'){if(!Array.isArray(value)||value.length>f.options.length||value.some(v=>!f.options.includes(v)))throw Error('複選內容不正確');out[f.key]=[...new Set(value)];}else{if(typeof value!=='string'||value.length>(['need','intro','purpose'].includes(sec.id)?1000:3000))throw Error('欄位格式或字數超限：'+f.label);if(f.type==='select'&&!f.options.includes(value))throw Error('選項不正確：'+f.label);out[f.key]=value;}}return out;});const clean=sec.repeat?result:result[0];if(JSON.stringify(clean).length>40000)throw Error('本段內容過長，請精簡後再存檔');return clean;}
function receipt_(sheet,id){if(sheet.getLastRow()<2)return null;const rows=sheet.getRange(2,1,sheet.getLastRow()-1,3).getValues();return rows.find(r=>r[0]===id)||null;}
function saveSection_(ss,d,sec,clean){const sheet=ss.getSheetByName(sheetName_(sec));if(!sheet)throw Error('教師尚未建立本段工作表');const existing=receipt_(sheet,d.requestId);if(existing){if(existing[2]!==d.projectId)throw Error('回執識別衝突');return {receipt:String(existing[0]),savedAt:String(existing[1])};}
 const student=student_(d.student),time=date_(),complete=sectionErrors(sec,clean).length===0,rows=sec.repeat?clean:[clean];
 const values=rows.map((row,i)=>[d.requestId,time,d.projectId,student.name,student.studentId,student.grade,student.className,student.track,complete?'段落必填完成':'草稿',i+1,...sec.fields.map(f=>{const v=row[f.key];return ['number','integer'].includes(f.type)&&v.trim()&&Number.isFinite(Number(v))?Number(v):v;}),i===0?JSON.stringify(clean):''].map(safeCell_));
 sheet.getRange(sheet.getLastRow()+1,1,values.length,values[0].length).setValues(values);SpreadsheetApp.flush();return {receipt:d.requestId,savedAt:time};}
function validateRequest_(d){if(d.schemaVersion!==2||typeof d.requestId!=='string'||!/^[a-zA-Z0-9-]{30,90}$/.test(d.requestId))throw Error('存檔識別碼不正確');student_(d.student);}
function saveSection(d){const ss=authorize_(d);validateRequest_(d);const sec=SCHEMA.find(s=>s.id===d.sectionId);if(!sec)throw Error('未知段落');const clean=sanitizeContent_(sec,d.content),lock=LockService.getScriptLock();lock.waitLock(30000);try{checkOwnership_(ss,d,true);return saveSection_(ss,d,sec,clean);}finally{lock.releaseLock();}}
function loadProposal(d){const ss=authorize_(d),lock=LockService.getScriptLock();lock.waitLock(30000);try{const owner=checkOwnership_(ss,d,false),sections={},saved={};let student={name:String(owner[3]),studentId:String(owner[4]),grade:String(owner[5]),className:String(owner[6]),track:String(owner[7])};SCHEMA.forEach(sec=>{const s=ss.getSheetByName(sheetName_(sec));if(!s||s.getLastRow()<2)return;const rows=s.getRange(2,1,s.getLastRow()-1,headers_(sec).length).getValues();for(let i=rows.length-1;i>=0;i--){const row=rows[i];if(row[2]!==d.projectId||!row[row.length-1])continue;sections[sec.id]=JSON.parse(row[row.length-1]);saved[sec.id]={at:String(row[1]),where:'Google Sheet',receipt:String(row[0])};break;}});return {sections,saved,student};}finally{lock.releaseLock();}}
function submitProposal(d){const ss=authorize_(d);validateRequest_(d);const clean={schemaVersion:2,student:student_(d.student),sections:{}};SCHEMA.forEach(sec=>clean.sections[sec.id]=sanitizeContent_(sec,d.sections?.[sec.id]));const errors=proposalErrors(clean);if(errors.length)throw Error(errors.slice(0,12).join('\n'));const lock=LockService.getScriptLock();lock.waitLock(30000);try{checkOwnership_(ss,d,true);const s=ss.getSheetByName('完整提交'),existing=receipt_(s,d.requestId);if(existing){if(existing[2]!==d.projectId)throw Error('回執識別衝突');return {receipt:String(existing[0]),savedAt:String(existing[1])};}SCHEMA.forEach(sec=>saveSection_(ss,{...d,requestId:d.requestId+'-'+sec.id},sec,clean.sections[sec.id]));const time=date_(),st=clean.student;s.appendRow([d.requestId,time,d.projectId,st.name,st.studentId,st.grade,st.className,st.track,'完整提交'].map(safeCell_));SpreadsheetApp.flush();return {receipt:d.requestId,savedAt:time};}finally{lock.releaseLock();}}
