const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const props={SHEET_ID:'mock',CLASS_CODE:'class-code'},sheets={},norm=v=>typeof v==='string'&&v.startsWith("'")?v.slice(1):v;
function makeSheet(name){const values=[];return sheets[name]={values,getLastRow:()=>values.length,getRange:(r,c,n=1,w=1)=>({setValues(matrix){assert.equal(matrix.length,n);matrix.forEach((row,i)=>{assert.equal(row.length,w);values[r-1+i]||=[];row.forEach((v,j)=>values[r-1+i][c-1+j]=norm(v));});return this},getValues:()=>Array.from({length:n},(_,i)=>Array.from({length:w},(_,j)=>values[r-1+i]?.[c-1+j]??'')),setBackground(){return this},setFontWeight(){return this},setWrap(){return this}}),appendRow:row=>values.push(row.map(norm)),setFrozenRows(){},setRowHeight(){}};}
let releases=0,created=0;const ss={getSheetByName:name=>sheets[name],insertSheet:makeSheet};
const context={console:{log(){}},Session:{getEffectiveUser:()=>({getEmail:()=> 'chatgpt.cjcu@gmail.com'})},PropertiesService:{getScriptProperties:()=>({getProperty:k=>props[k],setProperty:(k,v)=>props[k]=v})},SpreadsheetApp:{openById:()=>ss,create:()=>{created++;return {getId:()=> 'mock'}} ,flush(){}},LockService:{getScriptLock:()=>({waitLock(){},releaseLock(){releases++}})},Utilities:{DigestAlgorithm:{SHA_256:'sha256'},computeDigest:(algo,s)=>[...crypto.createHash(algo).update(s).digest()],formatDate:()=> '2026-10-07 13:00:00',getUuid:()=>crypto.randomUUID()}};
vm.createContext(context);vm.runInContext(fs.readFileSync('apps-script/Code.gs','utf8'),context);context.setup();assert.equal(Object.keys(sheets).length,23);assert.equal(created,0);
const schema=JSON.parse(fs.readFileSync('schema.json')),examples=JSON.parse(fs.readFileSync('examples.json'));
const base={schemaVersion:2,projectId:crypto.randomUUID(),editKey:crypto.randomUUID()+crypto.randomUUID(),requestId:crypto.randomUUID(),student:{name:'TEST學生',studentId:'00001234',grade:'四年級',className:'TEST班',track:'醫院品質管理企劃課'},classCode:'class-code',sectionId:'need',content:{text:''}};
assert.throws(()=>context.saveSection({...base,classCode:'wrong'}),/代碼/);
const a=context.saveSection(base),b=context.saveSection(base);assert.equal(a.receipt,b.receipt);assert.equal(sheets['壹｜訓練需求'].values.length,2);assert.equal(sheets['壹｜訓練需求'].values[1][4],'00001234');assert.equal(sheets['壹｜訓練需求'].values[1][8],'草稿');
const wrong={...base,editKey:crypto.randomUUID()+crypto.randomUUID()};assert.throws(()=>context.loadProposal(wrong),/密鑰/);assert.throws(()=>context.saveSection({...wrong,requestId:crypto.randomUUID()}),/密鑰/);
assert.throws(()=>context.saveSection({...base,requestId:crypto.randomUUID(),content:{text:'字'.repeat(1001)}}),/超限/);
assert.throws(()=>context.saveSection({...base,sectionId:'t5',content:[{...examples.t5[0],methods:['未知選項']}]}),/複選/);
const revised={...base,requestId:crypto.randomUUID(),content:{text:'已修訂需求'}};context.saveSection(revised);const loaded=context.loadProposal(base);assert.equal(loaded.sections.need.text,'已修訂需求');assert.equal(Object.keys(loaded.sections).length,1);
const d={...base,requestId:crypto.randomUUID(),sections:examples};assert.equal(vm.runInContext('proposalErrors',context)(d).length,0);
const teachingCase=JSON.parse(fs.readFileSync('cases/longcare-quality-newcomer.json'));assert.equal(vm.runInContext('proposalErrors',context)({...d,sections:teachingCase.sections}).length,0);
const records=fs.readFileSync('cases/synthetic-reports.csv','utf8').trim().split(/\r?\n/).slice(1);assert.equal(records.length,50);assert.equal(records.filter(line=>line.split(',')[5]==='1').length,30);
assert.throws(()=>context.submitProposal({...d,sections:{...examples,info:{...examples.info,hours:'10'}}}),/時數/);
const final=context.submitProposal(d),again=context.submitProposal(d);assert.equal(final.receipt,again.receipt);assert.equal(sheets['完整提交'].values.length,2);
const map=context.loadProposal(base);assert.equal(Object.keys(map.sections).length,21);assert.equal(map.sections.t1[0].taskId,'T1');
const t4=sheets['表4｜課程內容'].values[1];assert.equal(typeof t4[12],'number');
const author={...base,projectId:crypto.randomUUID(),editKey:crypto.randomUUID()+crypto.randomUUID(),requestId:crypto.randomUUID(),student:{name:'TEST作者',studentId:'不適用（作者）',grade:'不適用（教師／作者）',className:'TEST主辦單位',track:'宮廟管理職能導向種子師資培訓課程'}};
context.saveSection(author);assert.equal(context.loadProposal(author).student.className,'TEST主辦單位');assert.equal(context.loadProposal(author).student.grade,'不適用（教師／作者）');
assert.throws(()=>context.saveSection({...author,requestId:crypto.randomUUID(),student:{...author.student,studentId:'00001234'}}),/作者/);
context.Session.getEffectiveUser=()=>({getEmail:()=> 'joe.cjcu@gmail.com'});assert.throws(()=>context.setup(),/請用/);
assert.equal(context.safeCell_(' =IMPORTXML("x")'),'\' =IMPORTXML("x")');
console.log('PASS：21段23表、逐段草稿、學號文字、重送、續填、密鑰隔離、字數、選項、時數、整份提交、帳號限制');
